### ISSUE TITLE
How do we install this?

### ISSUE THREAD

**Issue by coolnow** [mmichaa/passafari.safariextension#1]
Forgive me if it's been written somewhere but i can't figure out a way to install this extension. I've only been using OSX for a few months so i hope i'm not missing something obvious.

**Comment by mmichaa** [comment]
Hey coolnow, it's not written somewhere. Because it's not in the Safari Extension Gallery (yet), you have to download and install it manually. Visit the project's releases page (https://github.com/mmichaa/passafari.safariextension/releases) and download the latest .safariextz file. To install the safari extension, just double click it in finder. Then Safari will ask you to install it or not. I hope that this helped you. Regards, Michael.

**Comment by coolnow** [comment]
Thank you for that link, i was trying to find the .safariextz on your
actual repo (new to this). Will try it soon!

**Comment by mmichaa** [comment]
Hey @coolnow , did you found a .safariextz yet?
