### ISSUE TITLE
Does this extension work on Safari 9?

### ISSUE THREAD

**Issue by Saren-Arterius** [mmichaa/passafari.safariextension#3]
I can connect this plugin to MacPass, but I can't auto-fill nor copying password from the extension.

**Comment by mmichaa** [comment]
Hey @Saren-Arterius, for me it works with Safari v9 _(currenty v9.0.3)_. But I never tried it with MacPass yet. I'm using "KyPass Companion" from the AppStore. But I will try MacPass in the next days and will report you, if it worked form me. Which version did you use?

**Comment by Saren-Arterius** [comment]
@mmichaa Compiled from latest git ATM

**Comment by mmichaa** [comment]
Hey @Saren-Arterius, I had some problems compiling the MacPassHTTP plugin. But now I have the latest MacPass with MacPassHTTP running. I'm currently using MacPass at mstarke/macpass@124acdc71508848ad83e1e58c92dd900e33c09e8 and MacPassHTTP at macpass/macpasshttp@d25162e38e63cd87a2c56ceb135a9c4ef017abf7. It works for mit in latest Chrome with chromelPass and it works for me with Safari 9.0.3 and passafari 1.0.beta2. Without changing any Settings of passafari, it gave me all my Passwords :see_no_evil: After I set the URL-Format to "Protocol & Host" it work as expected for me. I have to say that it was just a quick test and I only tested filling passwords for now.

**Comment by mmichaa** [comment]
... I have to say that it was just a quick test and I only tested filling passwords for now.

**Comment by mmichaa** [comment]
@Saren-Arterius does it work for you now?

**Comment by Saren-Arterius** [comment]
@mmichaa Lol I haven't used my Mac for a while. I will report back when I am available to test it out.

**Comment by netnut404** [comment]
I thought at first this was working for me, but it was actually from a saved passwords in safari with the apple keyring.  I then realized I have tried on several machines with EL Capitan and safari 9.0.3, and found the same result :-(

**Comment by mmichaa** [comment]
Hi @netnut404, it sounds like a usage problem. And because there is no usage description, it is a problem of the projects documentation. Did you try to hit the passafari button while you are on a login page? Nothing will happen unless you hit the button.

**Comment by issoft-nsiniakevich** [comment]
Hi @mmichaa,

I see that "Add new credentials" feature is already implemented.
Could you please describe how to use it?
And does it work with MacPass?

**Comment by mmichaa** [comment]
hi @issoft-nsiniakevich, I did a short test just now with MacPass v0.6.2 (12420). I tried it on twitter.com and it worked for me:
1. open twitter.com with safari
2. fill-in the sign-in form (with a "new" username, unknown to your database), but do not submit the form
3. now click on the passafari button
4. you should see an entry with a "+"-sign at the end of the list
5. click on the entry with the "+"-sign
6. switch to macpass and select the root of your database
7. you should see the created entry there

Updating an existing databaseentry works similar: fill-in a "known" username instead of a "new".

I hope it works four you too. Please tell me if it isn't :-)

**Comment by issoft-nsiniakevich** [comment]
@mmichaa cool, it works. 
Thank you.
